repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    - id: end-of-file-fixer
    - id: trailing-whitespace
-   repo: https://github.com/psf/black
    rev: 19.3b0
    hooks:
    - id: black
      args: [--line-length, "100", --target-version, py36]
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v0.720'
    hooks:
    - id: mypy
      name: mypy
      args: [--no-strict-optional, --ignore-missing-imports]
-   repo: https://github.com/pre-commit/mirrors-pylint
    rev: 'v2.3.1'
    hooks:
    - id: pylint
      args: [
          --disable, invalid-name,
          --disable, unidiomatic-typecheck,
          --disable, bad-continuation,
          --disable, missing-docstring,
          --disable, import-error,
          --disable, duplicate-code,
      ]
